# Proyecto de optimización con Álgebra Lineal

El álgebra lineal, una rama de las matemáticas un tanto compleja pero muy poderosa en áreas como la ingeniería, la ciencia y el Machine Learning. Entre los diferentes conceptos que maneja se encuentra el de **distancia**, utilizado para medir la separación entre dos puntos, conjuntos de puntos o funciones. 

Tal concepto es el que utilizarémos en el siguiente proyecto de optimización: Imagina que necesitamos arrendar un apartamento y tenemos tanta información de muchos de ellos que se nos dificulta organizar las citas, con lo cual, podríamos estar perdiendo una potencial oportunidad. La solución consiste en ordenar, según un orden de relevancia, las citas a partir de nuestro concepto de apartamento ideal. La **distancia** y la **norma** serán las herramientas que nos ayudarán a dar solución a este problema! Te invito a continuar con la lectura para 


# Conceptos de Algebra

# Análisis del problema

El gran problema es que llegamos a recolectar tanta informacion sobre anuncios y contactos que organizarnos para ir a las visitas puede parecer prácticamente imposible, dejando volar la oportunidad de un gran apartamento. La solucion que podemos dar al problema de las citas, mediante el algebra lineal, la podemos dividir en los siguientes pasos: 

1.- Representar nuestro departamento ideal como un vector de caracteristicas

2.- Construir el mismo vector para los apartamentos que ya tengamos localizados. 

3.- Calcular la distancia entre estos vectores y el vector que representa al departamento ideal.

4.- Ordenar, de manera ascendente, las distancias y ya tendríamos una lista ordenada en prioridad de contacto y visita de apartamentos según nuestro apartamento ideal.

# Implementacion de la Solucion

## Paso 1

Supongamos que las características de nuestro apartamento ideal son las siguientes:
- tamaño del apartamento
- número de recámaras
- número de baños
- número de estacionamientos. 

El tamaño del apartamento regularmente se da en metros cuadrados (área), cantidad que tiende a variar mucho, lo cual introduce una gran volumen de ruido. Para resolver este problema vamos a catalogar los tamaños de apartametos en categorias:

- 1 si el área es menor que 60 metros cuadrados
- 2 si el área es mayor o igual que 60 metros cuadrados pero menor que 80 metros cuadrados
- 3 si el área es mayor o igual que 80 metros cuadrados pero menor que 110 metros cuadrados
- 4 si el área es mayor o igual que 110 metros cuadrados pero menor que 130 metros cuadrados
- 5 si el área es mayor o igual que 130 metros cuadrados.

Nuestro apartamento ideal viene dado por el siguiente vector:

$$
\mathbf{I} = \begin{bmatrix} 3\\ 2\\ 2\\1 \end{bmatrix}
$$

donde: 
- El primer elemento con valor de 3 corresponde a la categoria de tamaño para un rango que va de los 80 a 110 metros cuadrados.
- El segundo elemento con valor de 2 esta asociado a la cantidad de recamaras.
- El tercer elemento con valor de 2 corresponde a la cantidad de baños.
- El cuarto elemento con valor de 1 corresponde al numero de estacionamiento.

Representamos el vector del apartamento ideal en Python como sigue:

In [12]:
# importamos la libreria Numpy
import numpy as np

# Vector de apartamento ideal
I = np.array([3,2,2,1])

I

array([3, 2, 2, 1])

## Paso 2

Ahora imaginemos que tenemos la informacion de 5 apartamentos. Al hacer la conversion como la hecha con el apartamento ideal, obtenemos los siguientes vectores:

$$
\mathbf{A_{1}} = \begin{bmatrix}4 \\3 \\ 3\\3 \end{bmatrix}, \qquad \mathbf{A_{2}} = \begin{bmatrix}3 \\3 \\ 2\\1 \end{bmatrix}, \qquad \mathbf{A_{3}} = \begin{bmatrix}5 \\4 \\ 3\\0 \end{bmatrix}, \qquad \mathbf{A_{4}} = \begin{bmatrix}1 \\2 \\ 1\\0 \end{bmatrix}, \qquad  \mathbf{A_{5}} = \begin{bmatrix}2 \\1 \\ 1\\2 \end{bmatrix}
$$

Representamos los vectores para cada apartamento en Python como sigue:

In [13]:
A_1 = np.array([4,3,3,3])
A_2 = np.array([3,3,2,1])
A_3 = np.array([5,4,3,0])
A_4 = np.array([1,2,1,0])
A_5 = np.array([2,1,1,0])

print(A_1)
print(A_2)
print(A_3)
print(A_4)
print(A_5)

[4 3 3 3]
[3 3 2 1]
[5 4 3 0]
[1 2 1 0]
[2 1 1 0]


## Paso 3

En este punto, el problema se reduce en encontrar el vector más cercano al vector ideal. Básicamente si tenemos una colección de N $n$-vectores $z_{0},z_{1},\dots,z_{N-1}$ vamos a decir que $z_{i}$ es el vecino más cercano del vector $x$ si 

$$
||x-z_{i}|| \le ||x - z_{j}|| \quad con \; \; j = 0,\dots, N-1
$$

Aca utilizamos la definicion de norma. Calculamos las distancias entre los vectores con la libreria Pandas como sigue:

In [14]:
print('||I-A_1|| =', np.linalg.norm(I - A_1))
print('||I-A_2|| =', np.linalg.norm(I - A_2))
print('||I-A_3|| =', np.linalg.norm(I - A_3))
print('||I-A_4|| =', np.linalg.norm(I - A_4))
print('||I-A_5|| =', np.linalg.norm(I - A_5))

||I-A_1|| = 2.6457513110645907
||I-A_2|| = 1.0
||I-A_3|| = 3.1622776601683795
||I-A_4|| = 2.449489742783178
||I-A_5|| = 2.0


## Paso 4

Como el resultado anterior es realizado sobre pocos apartamentos podemos visualizar de inmediato, sin necesidad de ordenar, que el apartamento con distancia mas pequeña que es el $A_{2}$. Sin embargo, para grandes cantidades esto podria ser un gran problema y aqui es importante ordenar las distancias de forma ascendente.

Para lograrlo vamos a crear una funcion que solicite un vector de vectores, el cual contendra todos los vectores de los apartamentos y aparte, el vector del apartamento ideal. La funcion devuelve un DataFrame con las distancias ordenadas.

In [15]:
# Creamos un vector de vectores con las distancias de los apartamentos
options = np.array([A_1,A_2,A_3,A_4,A_5])

options

array([[4, 3, 3, 3],
       [3, 3, 2, 1],
       [5, 4, 3, 0],
       [1, 2, 1, 0],
       [2, 1, 1, 0]])

In [16]:
# importamos la libreria Pandas
import pandas as pd

# Creamos la funcion
def ordenation(options,ideal):
    # creamos una lista vacia
    results = []

    # Contador
    index = 0

    # recorremos todos los vectores
    for option in options:
        index += 1

        # Generamos un array con el nombre y la distancia
        result = ['A_' + str(index), np.linalg.norm(ideal - option)]

        # guardamos el array en la lista results
        results.append(result)

    # Crea un df con los resultados ordenados
    df = pd.DataFrame(results, columns=['Departamento', 'Tasa']) #.nsmallest(1, 'Tasa')

    # ordena los resultados de forma ascendente 
    df = df.sort_values(by='Tasa', ascending=True)

    # Devuelve el dataframe
    return df

In [17]:
# llamamos la funcion con los parametros indicados
ordenation(options, I)

Departamento      Tasa
1          A_2  1.000000
4          A_5  2.000000
3          A_4  2.449490
0          A_1  2.645751
2          A_3  3.162278

De esta manera, ya tendremos la lista de los apartamentos a visitar ordenada en funcion de nuestras prioridades. Vemos que el apartamento que mas se ajusta a lo que buscamos es el $A_{2}$ seguido del $A_{5}$. Ahora solo queda discutir las condiciones y un poco el precio para quedarnos con ello!

# Caracteristicas de mayor prioridad

Imagina que de las caracteristicas de nuestro apartamento ideal damos mayor relevancia al numero de recamaras y al numero de parqueaderos. Como podemos reflejar estas preferencias a la hora de ordenar las citas?. La respuesta es agregando una ponderacion de importancia sobre cada caracteristica.

Para lograrlo, creamos un vector de ponderacion con valores entre 0 y 1 para cada caracteristica los cuales representan la importancia que le damos a cada una. Mientras mas cercano a 1 mayor es la importancia dada:

- Tamaño del apartamento: 0.3
- Numero de recamaras: 0.9
- Numero de baños: 0.4
- Numero de parqueaderos: 1

Al numero de recamaras y al numero de parqueadero damos valores cercanos a 1. Creamos el vector con la libreria Numpy de Python como sigue: 

In [18]:
arr_pond = np.array([
                     0.3, # tamano apartamento
                     0.9, # numero de recamaras
                     0.4, # numero de banos
                     1    # numero de parqueaderos
                     ])

Lo siguiente es crear una funcion que pondere los valores de un vector con el vector de ponderacion dado (arr_pond). Recuerda que el vector de ponderacion debe tener las misma dimensiones que los demas vectores.

In [22]:
#Funcion de ponderacion de vectores
def pond(vect, arr_pond=arr_pond):
    return vect * arr_pond

Finalmente, creamos una funcion como la del Paso 4 que refleje la ponderacion de importancia.

In [23]:
# Funcion de ordenacion considerando ponderacion de importancia
def ordenationPond(options,ideal):
    
    # creamos una lista vacia
    results = []

    # Contador
    index = 0

    # recorremos todos los vectores
    for option in options:
        index += 1

        # Generamos un array con el nombre y la distancia
        result = ['A_' + str(index), np.linalg.norm(pond(ideal) - pond(option))]

        # guardamos el array en la lista results
        results.append(result)

    # Crea un df con los resultados ordenados
    df = pd.DataFrame(results, columns=['Departamento', 'Tasa']) #.nsmallest(1, 'Tasa')

    # ordena los resultados de forma ascendente 
    df = df.sort_values(by='Tasa', ascending=True)

    # Devuelve el dataframe
    return df

Ahora, llamamos la funcion ordenationPond y le pasamos el vector de vectores de los apartamentos y el vector de nuestro apartamento ideal

In [24]:
ordenationPond(options,I)

Departamento      Tasa
1          A_2  0.900000
3          A_4  1.232883
4          A_5  1.435270
2          A_3  2.181742
0          A_1  2.249444

Ahora vemos como la lista de citas a cambiado. A pesar que el apartamento $A_{2}$ siguen siendo el que mas se ajusta a lo que buscamos, el apartamento $A_{5}$ ya no es el siguiente sino que es el $A_{4}$.