# Dimension de las representaciones

In [2]:
# libreria para manejar arreglos
import numpy as np

In [3]:
# definimos un escalar
escalar = 5.679
# vector
vector = np.array([1,2,3])
# matriz
matriz = np.array([[1,2],[3,4]])
# tensor
tensor = np.array([
    [[1,2,3],[4,5,6],[6,7,8]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [4]:
# mostramos escalar
print(escalar)

5.679


In [5]:
# como el escalar no tiene dimension, se muestra un error
escalar.shape

AttributeError: 'float' object has no attribute 'shape'

In [6]:
# dimension del vector
vector.shape

(3,)

In [7]:
# mostrar el vector
print(vector)

[1 2 3]


In [8]:
# size del vector
len(vector)

3

In [9]:
# dimension de la matriz
matriz.shape

(2, 2)

In [10]:
# mostrar matriz
print(matriz)

[[1 2]
 [3 4]]


In [11]:
# size de la matriz
len(matriz)

2

In [13]:
# cantidad de elementos de la matriz
print(matriz.size)

4


In [14]:
# dimensiones del tensor
print(tensor.shape)

(3, 3, 3)


In [16]:
#mostrar tensor
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [17]:
# size del tensor
len(tensor)

3

In [19]:
# cantidad de elementos del tensor
print(tensor.size)

27
