# Transposicion

In [1]:
# libreria para manipular elementos
import numpy as np

In [2]:
# definimos algunos elementos

scalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30], [4,5,6,31], [7,8,9,32]],
    [[11,12,13,33], [14,15,16,34], [17,18,19,35]],
    [[21,22,23,36], [24,25,26,37], [27,28,29,38]]
])

__Transpuesta de un escalar__

In [3]:
escalar_t = scalar.T

AttributeError: 'float' object has no attribute 'T'

Arroja un error dedibo a que un escalar no tiene dimensiones, por tanto no se puede intercambiar filas por columnas.

__Transpuesta de un vector__

In [4]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


En Python, la representacion de un vector transpuesto no tiene mayor diferencia con uno normal. La diferencia se nota a la hora de realizar operaciones.

__Transposicion de una matriz__

Definimos a la matriz transpuesta como la matriz a la que invertimos las posiciones, es decir invertimos las filas por las columnas. Si teníamos una matriz de dimensiones $mxn$ su transpuesta será una matriz de dimensión $nxm$

In [7]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# dimensiones de la matriz
matriz.shape

(3, 2)

In [5]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [9]:
# dimensiones de la matriz traspuesta
matriz_t.shape

(2, 3)

__Transposicion de un tensor__

Un tensor también se puede transponer en este caso se intercambiaran los elementos de manera que la jerarquía quede invertida. Sea un tensor de $mxnxp$ el tensor transpuesto tendrá una dimensión de $pxnxm$

In [10]:
tensor

array([[[ 1,  2,  3, 30],
        [ 4,  5,  6, 31],
        [ 7,  8,  9, 32]],

       [[11, 12, 13, 33],
        [14, 15, 16, 34],
        [17, 18, 19, 35]],

       [[21, 22, 23, 36],
        [24, 25, 26, 37],
        [27, 28, 29, 38]]])

In [11]:
# dimensiones del tensor
tensor.shape

(3, 3, 4)

In [12]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [13]:
# dimensiones del tensor transpuesto
tensor_t.shape

(4, 3, 3)

__Transponer una matriz transpuesta__

In [14]:
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
# matriz original
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

# Suma de vectores - Matrices

Vamos a definir la matriz anterior como A y la matriz transpuesta matriz_t como B

In [16]:
A = matriz
B = matriz_t

Como la suma de matrices está definida para matrices de las mismas dimensiones, al sumar las matrices A y B, nos arroja un error de dimension.

In [17]:
C = A + B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Definamos dos matrices de las mismas dimensiones!

In [18]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[6,5], [4,3], [2,1]])

In [19]:
# sumamos las matrices anteriores
C = A + B
print(C)

[[7 7]
 [7 7]
 [7 7]]


Vamos a sumar a "matriz" el escalar "scalar" a ver que resulta

In [20]:
C = matriz + scalar
print(C)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
