# Propiedades del Producto Interno

In [1]:
# importamos la libreria
import numpy as np

In [2]:
# definimos las matrices con las que vamos a trabajar
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

### 1. Verifiquemos si es asociativa

$$Ax(BxC) = (AxB)xC$$

In [4]:
A_BC = A.dot(B.dot(C))
print(A_BC)

[[ 60  26]
 [145  63]
 [295 129]]


In [5]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


> El producto interno es asociativo

### 2. Verifiquemos si es distributiva

$$Ax(B+C) = (AxB) + (AxC)$$

In [6]:
D = A.dot(B+C)
print(D)

[[ 26  17]
 [ 62  41]
 [122  83]]


In [7]:
E = (A.dot(B))+(A.dot(C))
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]


> El producto interno es distributivo