# Propiedades del Producto Interno

In [1]:
# importamos la libreria
import numpy as np

In [2]:
# definimos las matrices con las que vamos a trabajar
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

### 1. Verifiquemos si es asociativa

$$A\cdot(B\cdot C) = (A\cdot B)\cdot C$$

In [4]:
A_BC = A.dot(B.dot(C))
print(A_BC)

[[ 60  26]
 [145  63]
 [295 129]]


In [5]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


> El producto interno es asociativo

### 2. Verifiquemos si es distributiva

$$A\cdot(B+C) = (A\cdot B) + (A\cdot C)$$

In [6]:
D = A.dot(B+C)
print(D)

[[ 26  17]
 [ 62  41]
 [122  83]]


In [7]:
E = (A.dot(B))+(A.dot(C))
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]


In [8]:
# comparemos las matrices resultantes elemento a elemento
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


> El producto interno es distributivo

### 3. Verifiquemos si es conmutativa

$$B\cdot C = C\cdot B$$

In [9]:
F = B.dot(C)
print(F)

[[15  7]
 [10  4]]


In [10]:
G = C.dot(B)
print(G)

[[ 5 10]
 [ 8 14]]


In [11]:
# verifiquemos elemento a elemento
print(F==G)

[[False False]
 [False False]]


> El producto interno no es conmutativo

### 4. Conmutatividad en vectores

$$B\cdot C = C\cdot B$$

In [14]:
# definimos dos vectores
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [15]:
# probamos la conmutatividad
v1t_v2 = v1.T.dot(v2)
print(v1t_v2)

[[41]]


In [16]:
v2t_v1 = v2.T.dot(v1)
print(v2t_v1)

[[41]]


> El producto interno entre vectores es conmutativo.

> Tener en cuenta la trasnpuesta de uno de los vectores para obtener el producto interno.

### 5. Conmutatitividad en matrices cuadradas

La ley conmutativa solo aplica en la multiplicación de matrices cuando éstas son matrices cuadradas y al mismo tiempo son matrices diagonales.

In [18]:
# definimos dos matrices cuadradas
A = np.array([[7, 0, 0, 0], [0, 5, 0, 0], [0, 0, 2, 0], [0, 0, 0, 20]])
B = np.array([[1, 0, 0, 0], [0, 8, 0, 0], [0, 0, 13, 0], [0, 0, 0, 4]])

print(A)
print(B)

[[ 7  0  0  0]
 [ 0  5  0  0]
 [ 0  0  2  0]
 [ 0  0  0 20]]
[[ 1  0  0  0]
 [ 0  8  0  0]
 [ 0  0 13  0]
 [ 0  0  0  4]]


In [19]:
# probamos la conmutatividad
AB = A.dot(B)
print(AB)

[[ 7  0  0  0]
 [ 0 40  0  0]
 [ 0  0 26  0]
 [ 0  0  0 80]]


In [20]:
BA = B.dot(A)
print(BA)

[[ 7  0  0  0]
 [ 0 40  0  0]
 [ 0  0 26  0]
 [ 0  0  0 80]]


In [21]:
# comparamos elemento a elemento
print(AB==BA)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


> El producto interno de matrices cuadradas diagonales es conmutativo.