# Matriz Identidad

Es el elemento neutro de la multiplicación de matrices. Es decir que cualquier matriz multiplicada por la matriz identidad resulta la misma matriz. Es una matriz cuadrada con unos en la diagonal y ceros en los demas elementos.

In [2]:
# importamos librerias
import numpy as np

# matriz identidad 4x4
identidad = np.eye(4)

print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


> Notamos que los valores estan definidos como float. Esto quiere decir que aunque estemos operando con un vector de enteros, lo que vamos a recibir son float.

Para obtener la matriz identidad con elementos enteros procedemos como sigue

In [3]:
identidad = np.eye(4, dtype=int)
print(identidad)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Definamos un vectorn de 4 dimensiones

In [4]:
vector = np.array([[2], [3], [5], [7]])
print(vector)

[[2]
 [3]
 [5]
 [7]]


Ahora, vamos a realizar el producto interno entre el _vector_ y la matriz _Identidad_

In [5]:
print(identidad.dot(vector))

[[2]
 [3]
 [5]
 [7]]


Como vemos, obtenemos el mismo vector.

# Matriz Inversa

La matriz inversa cumple una función similar al concepto de inverso en la multiplicación usual: cuando una matriz ( A ) se multiplica por su inversa ( A^{-1} ), obtenemos la matriz identidad.

Vamos a crear una matriz 3x3 para luego obtener su inversa

In [6]:
A = np.array([[1,0,1], [0,1,1], [-1,1,1]])
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


Para hallar la inversa de $A$, utilizamos el metodo _linalg.inv_ de numpy.

In [7]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


Ahora, para saber si _inversa_A_ es realmente la inversa de $A$ se debe cumplir que el producto interno entre _A_ y _inversa_A_ arroje la matriz identidad.

In [8]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


> Vemos que obtenemos la matriz identidad.

> Es importante tener en cuenta que no siempre existe la matriz inversa. Cuando no existe la inversa, llamamos a la matriz _singular._

# Matriz Singular

Una matriz es singular cuando no tiene inversa. Todas las matrices que no son cuadradas son singulares.

Definamos una matriz

In [9]:
B = np.array([[1,1], [1,1]])
print(B)

[[1 1]
 [1 1]]


Calculamos la inversa de $B$

In [10]:
print(np.linalg.inv(B))

LinAlgError: Singular matrix

El error indica que se trata de una matriz singular

# Conclusiones

> No se puede calcular la matriz inversa de una matriz que no sea cuadrada.

> La matriz inversa permite resolver el siguiente problema:

$$Ax=B$$
    de la siguiente forma
$$x = BA^{-1}$$

> Si una matriz no tiene inversa se dice que es Singular.