# Reto 7

### 1. Crear un objeto de tipo ndarray, con números enteros entre 64 hasta 1024.

In [1]:
# importamos libreria de numpy
import numpy as np

In [4]:
# creamos el ndarray con numeros enteros desde 64 hasta 1024
arreglo = np.arange(64, 1025)
arreglo 

array([  64,   65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
         75,   76,   77,   78,   79,   80,   81,   82,   83,   84,   85,
         86,   87,   88,   89,   90,   91,   92,   93,   94,   95,   96,
         97,   98,   99,  100,  101,  102,  103,  104,  105,  106,  107,
        108,  109,  110,  111,  112,  113,  114,  115,  116,  117,  118,
        119,  120,  121,  122,  123,  124,  125,  126,  127,  128,  129,
        130,  131,  132,  133,  134,  135,  136,  137,  138,  139,  140,
        141,  142,  143,  144,  145,  146,  147,  148,  149,  150,  151,
        152,  153,  154,  155,  156,  157,  158,  159,  160,  161,  162,
        163,  164,  165,  166,  167,  168,  169,  170,  171,  172,  173,
        174,  175,  176,  177,  178,  179,  180,  181,  182,  183,  184,
        185,  186,  187,  188,  189,  190,  191,  192,  193,  194,  195,
        196,  197,  198,  199,  200,  201,  202,  203,  204,  205,  206,
        207,  208,  209,  210,  211,  212,  213,  2

### 2. Redimensionar a una matriz bidimensional que tenga las 1024 observaciones, pero que su dimensión tenga tanto el mismo número de filas como de columnas, con la finalidad de obtener una cuadrada.

In [6]:
# creamos un ndarray con 1024 numero enteros
arr = np.arange(1, 1025)

# utilizamos el metodo reshape para redimensionar arr
matriz = arr.reshape(32, 32)
matriz

array([[   1,    2,    3, ...,   30,   31,   32],
       [  33,   34,   35, ...,   62,   63,   64],
       [  65,   66,   67, ...,   94,   95,   96],
       ...,
       [ 929,  930,  931, ...,  958,  959,  960],
       [ 961,  962,  963, ...,  990,  991,  992],
       [ 993,  994,  995, ..., 1022, 1023, 1024]])

### 3. Crear una columna de datos aleatorios de 30 observaciones o registros, en la que se escojan dichos registros desde una lista de 10 nombres. Se debe repetir el proceso anterior para crear un set de números de cédulas aleatorio para cada uno de los nombres.

In [7]:
# lista de nombres
nombres =['Andres', 'Maria', 'Manuel', 'Daniel', 'Sarah', 'Cristian', 'Violetta', 'Lucia', 'Jackson', 'Jose']
nombres

['Andres',
 'Maria',
 'Manuel',
 'Daniel',
 'Sarah',
 'Cristian',
 'Violetta',
 'Lucia',
 'Jackson',
 'Jose']

In [8]:
# columna de 30 observaciones aleatorias de los nombres
col_nombres = np.random.choice(nombres, 30)
col_nombres

array(['Lucia', 'Daniel', 'Daniel', 'Violetta', 'Cristian', 'Jose',
       'Maria', 'Daniel', 'Jackson', 'Maria', 'Sarah', 'Violetta',
       'Andres', 'Manuel', 'Cristian', 'Lucia', 'Jose', 'Sarah', 'Daniel',
       'Manuel', 'Manuel', 'Sarah', 'Lucia', 'Violetta', 'Lucia',
       'Daniel', 'Sarah', 'Sarah', 'Jose', 'Maria'], dtype='<U8')

In [9]:
# columna de cedulas aleatorias (entre 10 y 99 millones)
col_cedulas = np.random.randint(10000000, 99000000, 30)
col_cedulas

array([16016767, 42856790, 22563033, 55473259, 29878835, 81732903,
       90456468, 80603276, 93282221, 34015442, 46645162, 94841300,
       61294191, 67284748, 11131370, 31204244, 25920452, 32125386,
       92010516, 58205253, 23939173, 48441819, 86699993, 96482008,
       56903825, 84137047, 58194130, 12398992, 45899471, 18605550])

### 4. Concatenar un nuevo vector con las observaciones de los nombres y cédulas.

In [12]:
cols_concatenadas = np.column_stack((col_nombres, col_cedulas))
cols_concatenadas

array([['Lucia', '16016767'],
       ['Daniel', '42856790'],
       ['Daniel', '22563033'],
       ['Violetta', '55473259'],
       ['Cristian', '29878835'],
       ['Jose', '81732903'],
       ['Maria', '90456468'],
       ['Daniel', '80603276'],
       ['Jackson', '93282221'],
       ['Maria', '34015442'],
       ['Sarah', '46645162'],
       ['Violetta', '94841300'],
       ['Andres', '61294191'],
       ['Manuel', '67284748'],
       ['Cristian', '11131370'],
       ['Lucia', '31204244'],
       ['Jose', '25920452'],
       ['Sarah', '32125386'],
       ['Daniel', '92010516'],
       ['Manuel', '58205253'],
       ['Manuel', '23939173'],
       ['Sarah', '48441819'],
       ['Lucia', '86699993'],
       ['Violetta', '96482008'],
       ['Lucia', '56903825'],
       ['Daniel', '84137047'],
       ['Sarah', '58194130'],
       ['Sarah', '12398992'],
       ['Jose', '45899471'],
       ['Maria', '18605550']], dtype='<U21')

### 5. Mostrar la posición del número más grande de las cédulas generadas del vector creado en el punto 4. Se debe investigar Slicing notation en numpy.

In [13]:
# encontrar la posicion del numero de cedula mas grande
pos_max_cedula = np.argmax(col_cedulas)
print(f'Posicion del numero mas grande de cedula es: {pos_max_cedula}')

Posicion del numero mas grande de cedula es: 23


In [14]:
# Nombre y cedula correspondiente al valor maximo
print(f'Nombre asociado: {cols_concatenadas[pos_max_cedula, 0]}')
print(f'Cadula mas grande: {cols_concatenadas[pos_max_cedula, 1]}')

Nombre asociado: Violetta
Cadula mas grande: 96482008
