# Librerias para el Procesamiento de Datos

## Cargar Librerias

In [2]:
import pandas as pd
import numpy as np

## Numpy

Biblioteca dedicada a procesar valores numericos y se enfoca en el algebra lineal

### Crear un Vector

In [3]:
# crear un vector
vector = np.array([2,7,4])
vector

array([2, 7, 4])

- Importamos la libreria *Numpy* con un alias llamado *np*.

- Utilizamos el metodo *.array()* para crear el vector con los datos proporcionados. Soporta objetos indexados.

- El metodo *array()* pertenece a la biblioteca *Numpy* para crear datos ordenados conocidos como vectores y matrices.

### Crear una Matriz

In [4]:
matriz = np.array([[2,4,1], [3,6,9], [9,5,1]])
matriz

array([[2, 4, 1],
       [3, 6, 9],
       [9, 5, 1]])

- Al crear una matriz, puedes declarar todos los datos en una sola linea separandolos por una coma. Este tipo de datos se llama *ndarray* el cual se caracteriza porque todos sus datos son del mismo tipo.

### Producto de un Vector por una Matriz

In [5]:
result = vector @ matriz
result

array([61, 70, 69])

- El producto entre un vector y una matriz se realiza mediante el operador *@* que Numpy lo identifica como poducto. Para que se ejecute correctamente la operacion, ambos elementos deben ser de la misma operacion.

### Calculo de la inversa de una Matriz

In [7]:
from numpy import linalg

matrizInv = linalg.inv(matriz)
matrizInv

array([[-2.00000000e-01,  5.12820513e-03,  1.53846154e-01],
       [ 4.00000000e-01, -3.58974359e-02, -7.69230769e-02],
       [-2.00000000e-01,  1.33333333e-01,  9.86864911e-18]])

- Para obtener la inversa de una matriz, llamamos al metodo *.inv()* de la clase **linalg** de la biblioteca Numpy el cual importamos mediante la instruccion **from numpy import linalg**

- Recuerda que los metodos de una clase se pueden visualizar con la instruccion *dir()*