# Librerias para el Procesamiento de Datos

## Cargar Librerias

In [2]:
import pandas as pd
import numpy as np

## Numpy

Biblioteca dedicada a procesar valores numericos y se enfoca en el algebra lineal

### Crear un Vector

In [3]:
# crear un vector
vector = np.array([2,7,4])
vector

array([2, 7, 4])

- Importamos la libreria *Numpy* con un alias llamado *np*.

- Utilizamos el metodo *.array()* para crear el vector con los datos proporcionados. Soporta objetos indexados.

- El metodo *array()* pertenece a la biblioteca *Numpy* para crear datos ordenados conocidos como vectores y matrices.

### Crear una Matriz

In [4]:
matriz = np.array([[2,4,1], [3,6,9], [9,5,1]])
matriz

array([[2, 4, 1],
       [3, 6, 9],
       [9, 5, 1]])

- Al crear una matriz, puedes declarar todos los datos en una sola linea separandolos por una coma. Este tipo de datos se llama *ndarray* el cual se caracteriza porque todos sus datos son del mismo tipo.

### Producto de un Vector por una Matriz

In [5]:
result = vector @ matriz
result

array([61, 70, 69])

- El producto entre un vector y una matriz se realiza mediante el operador *@* que Numpy lo identifica como poducto. Para que se ejecute correctamente la operacion, ambos elementos deben ser de la misma operacion.

### Calculo de la inversa de una Matriz

In [7]:
from numpy import linalg

matrizInv = linalg.inv(matriz)
matrizInv

array([[-2.00000000e-01,  5.12820513e-03,  1.53846154e-01],
       [ 4.00000000e-01, -3.58974359e-02, -7.69230769e-02],
       [-2.00000000e-01,  1.33333333e-01,  9.86864911e-18]])

- Para obtener la inversa de una matriz, llamamos al metodo *.inv()* de la clase **linalg** de la biblioteca Numpy el cual importamos mediante la instruccion **from numpy import linalg**

- Recuerda que los metodos de una clase se pueden visualizar con la instruccion *dir()*

In [9]:
print(dir(linalg))

['LinAlgError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'cholesky', 'cond', 'det', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


### Metodo *randint()*

El metodo *.randint()* permite generar un numero entero aleatorio entre 0 y 100. Pertenece a la clase *random* de la libreria **Numpy**

In [16]:
from numpy import random

x = random.randint(100)
x

32

- Al pasar como argumento el numero 100, indica que el rango para elegir el numero va entre 0 y 100. Si cambiamos el argumento, cambia el rango de eleccion

In [15]:
y = random.randint(10)
y

3

**Vector con elementos aleatorios enteros**

In [17]:
x = random.randint(10, size=(5))
x

array([9, 4, 9, 6, 3])

- El agumento *size()* indica la cantidad de elementos a crear y ademas si solo contiene un valor genera un vector.

**Matriz con elementos aleatorios enteros**

In [18]:
x = random.randint(10, size=(5,7))
x

array([[6, 0, 1, 0, 0, 2, 5],
       [2, 1, 1, 1, 0, 6, 6],
       [9, 1, 5, 8, 4, 6, 5],
       [4, 8, 2, 6, 8, 7, 6],
       [1, 2, 1, 1, 5, 9, 0]])

- Si el argumento *size()* posee dos valores, crea una matriz donde el primer valor indica las filas y el segundo valor las columnas.

### Metodo *rand()*

El metodo *.rand()* devuelve un numero float aleatorio entre 0.0 y 1.0. Pertenece a la clase *random* de la libreria **Numpy**.

In [11]:
from numpy import random

y = random.rand()
y

0.6325929018917967

- Al usar el metodo *rand()* sin argumentos, genera un solo dato. Podemos especificar la cantidad de datos usando un numero entero.

**Vector con elementos aleatorios float**

In [12]:
# crea 4 numero float aleatorios que esten entre 0.0 y 1.0
x = random.rand(4)
x

array([0.65452395, 0.07057304, 0.53332826, 0.68750796])

In [13]:
type(x)

numpy.ndarray

- Al pasar el 4 como argumento, se crea un vector de 4 elementos aleatorios de tipo float. Esto lo verificamos con la funcion *type()* que arroja que el objeto creado es de tipo *ndarray*

**Matriz de elementos aleatorios float**

In [14]:
from numpy import random

x = random.rand(4, 2)
x

array([[0.51052295, 0.46081872],
       [0.70487954, 0.87607524],
       [0.08174894, 0.68755407],
       [0.99736985, 0.32175702]])

- El primer elemento hace referencia a las filas. Mientras que el segundo elemento indica la cantidad de columnas