# Librerías en Python - Google Colab

## Libreria propia de Python

In [2]:
# Built - in Function
# entrada
A = input('Digite un mensaje: ')

hola


In [3]:
# imprimir
print(A)

hola


In [4]:
# tipo de dato
type(A)

str

## Importar y Modulos

Importar una librería y todos sus métodos. En este caso, vamos a utilizar la libreria de Numpy

In [1]:
# importar libreria y agregar un alias
import numpy as np

Puedes acceder a todos los métodos de la libreria _numpy_ utilizando el prefijo __np.__

In [2]:
#Creando una lista
numeros = [3,5,1,7,9]

In [3]:
# Convertir la lista en un array con numpy
arreglo = np.array(numeros)
arreglo

array([3, 5, 1, 7, 9])

In [4]:
# Sumar todos los elementos
np.sum(arreglo)

25

In [5]:
# Calcular la media
np.mean(arreglo)

5.0

Para verificar el tipo de datos, puedes usar la función incorporada de Python _type()_. Esto te permitirá ver qué tipo de dato tiene una variable o resultado de una operación.

In [6]:
#Verificando los tipos de datos en nuestras salidas
type(np.mean(arreglo))

numpy.float64

La instrucción _from ... import_ se utiliza para importar módulos específicos o componentes de un módulo, lo que te permite acceder a ellos directamente sin necesidad de escribir el nombre completo del módulo.

In [7]:
# importar solo los metodos array y linspace de Numpy
from numpy import array, linspace

In [8]:
#Convertir lista en array
array([3,6,8,1])

array([3, 6, 8, 1])

In [11]:
# generar 5 numeros en intervalos iguales entre el 0 y 10
linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Referencias o Instanciación

Podemos simplificar el nombre del metodo importado para mejorar la sintaxis

In [12]:
from numpy import array as arr

In [13]:
arr([2,4,1])

array([2, 4, 1])

- La ventaja de importar funciones específicas es que puedes mejorar la legibilidad del codigo. Es util solo cuando necesitas unas pocas funciones

- La ventaja de importar todo con import es que tienes todas las funcionalidades de la libreria a tu alcance. La desventaja es que puede que importe más funciones de las necesarias, ocupando gran espacio.

### Ejercicio: referenciar o re-nombrar las siguientes librerías. (pandas, matplotlib, scipy)

In [1]:
# Ejemplo de como renombrar las librerías
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp

Nota: Es importante aclarar, que la referencia o el proceso de re-nombrar una librería, puede colocarse cualquier nombre. No obstante, se busca que el nombre sea simple y coherente con el paquete o solución a utilizar.

In [5]:
# Ejemplo de un mal proceso de renombrar una librería
import numpy as random_name

- __Falta de claridad__: Usar un alias como random_name no da ninguna pista sobre la librería que realmente se está utilizando.

- __Dificultad en la lectura del código__: Otros desarrolladores (e incluso tú mismo en el futuro) tendrán problemas para entender rápidamente qué librería estás usando.

- __Error potencial__: El nombre podría entrar en conflicto con variables o funciones que tengan un nombre similar, lo que aumenta la posibilidad de errores.

Nota: una mala práctica al renombrar una librería ocurre cuando el alias que se le da a la librería es ambiguo, demasiado largo, o no refleja su propósito.

In [2]:
import pandas as data_handling_library

- A pesar de que funciona sin problemas, no es una buena practica.

- Lo mejor que se puede usar son dos o maximo 3 caracteres para renombrar



In [4]:
import pandas as pd

## Instalación de Librerías

In [ ]:
#La instalación de librerias se realiza bajo el siguiente comando
#!pip install nombreLibrería
#Para este ejemplo, utilizaremos la librería pandas, la cual instalaremos


In [ ]:
#Para instalar una versión en especifico, se realiza con el comando
#!pip install nombreLibreria==0.9.0


## Verificar versiones del stack de librerías en el entorno de trabajo

In [ ]:
#Podremos consultar la lista del stack de pibrerias de nuestro entorno de ejecusión en google colab


##Saber sobre una librería en específico

In [ ]:
#Podremos consultar sobre una librería en especifico con el comando help!!!
#Para este caso, consultaremos información de la librería tensorflow
