# Librerías en Python

Son un conjunto de soluciones predefinidas. Es una suite de herramientas que otros han desarrollado para ser utilizadas en cualquier nuevo proyecto para agilizar algunas características o funcionalidades de una aplicación o sistema en construcción.

## Libreria interna de Python

Denominadas built-in functions o librerías del sistema, son aquellas que no requieren ser instaladas para usarla ya que son propias del lenguaje.

Consulta las librerias estandar de Python [Aqui]('https://docs.python.org/3/library/functions.html')

In [2]:
# Built - in Function
# entrada
A = input('Digite un mensaje: ')

hola


In [3]:
# imprimir
print(A)

hola


In [4]:
# tipo de dato
type(A)

str

## Importar y Modulos

Para importar librerías y todos sus métodos se utiliza la siguiente sintaxis:

- Se invoca dicha librería a través de la sentencia (import)
en minúscula. 

- Las librerías tienen, por lo general, elementos internos tales como métodos y funciones, que para ser usados se
debe invocar mediante la nomenclatura del punto (.)

In [6]:
# importar libreria
import numpy

Puedes acceder a todos los métodos de la libreria _numpy_ utilizando el nombre __numpy.__

In [8]:
#Creando una lista
numeros = [3,5,1,7,9]

In [9]:
# Convertir la lista en un array con numpy
arreglo = numpy.array(numeros)
arreglo

array([3, 5, 1, 7, 9])

In [10]:
# Sumar todos los elementos
numpy.sum(arreglo)

25

In [11]:
# Calcular la media
numpy.mean(arreglo)

5.0

Para verificar el tipo de datos, puedes usar la función incorporada de Python _type()_. Esto te permitirá ver qué tipo de dato tiene una variable o resultado de una operación.

In [12]:
#Verificando los tipos de datos en nuestras salidas
type(numpy.mean(arreglo))

numpy.float64

Para conoces todas las funciones y metodos que trae una libreria utilizamos la funcion propia _dir()_.

In [13]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

La instrucción _from ... import_ se utiliza para importar módulos específicos o componentes de un módulo, lo que te permite acceder a ellos directamente sin necesidad de escribir el nombre completo del módulo.

In [7]:
# importar solo los metodos array y linspace de Numpy
from numpy import array, linspace

In [8]:
#Convertir lista en array
array([3,6,8,1])

array([3, 6, 8, 1])

In [11]:
# generar 5 numeros en intervalos iguales entre el 0 y 10
linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Referencias o Instanciación

Podemos simplificar el nombre del metodo importado para mejorar la sintaxis

In [12]:
from numpy import array as arr

In [13]:
arr([2,4,1])

array([2, 4, 1])

- La ventaja de importar funciones específicas es que puedes mejorar la legibilidad del codigo. Es util solo cuando necesitas unas pocas funciones

- La ventaja de importar todo con import es que tienes todas las funcionalidades de la libreria a tu alcance. La desventaja es que puede que importe más funciones de las necesarias, ocupando gran espacio.

### Ejercicio: referenciar o re-nombrar las siguientes librerías. (pandas, matplotlib, scipy)

In [1]:
# Ejemplo de como renombrar las librerías
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp

Nota: Es importante aclarar, que la referencia o el proceso de re-nombrar una librería, puede colocarse cualquier nombre. No obstante, se busca que el nombre sea simple y coherente con el paquete o solución a utilizar.

In [5]:
# Ejemplo de un mal proceso de renombrar una librería
import numpy as random_name

- __Falta de claridad__: Usar un alias como random_name no da ninguna pista sobre la librería que realmente se está utilizando.

- __Dificultad en la lectura del código__: Otros desarrolladores (e incluso tú mismo en el futuro) tendrán problemas para entender rápidamente qué librería estás usando.

- __Error potencial__: El nombre podría entrar en conflicto con variables o funciones que tengan un nombre similar, lo que aumenta la posibilidad de errores.

Nota: una mala práctica al renombrar una librería ocurre cuando el alias que se le da a la librería es ambiguo, demasiado largo, o no refleja su propósito.

In [2]:
import pandas as data_handling_library

- A pesar de que funciona sin problemas, no es una buena practica.

- Lo mejor que se puede usar son dos o maximo 3 caracteres para renombrar



In [4]:
import pandas as pd

## Instalación de Librerías

In [ ]:
#La instalación de librerias se realiza bajo el siguiente comando
#!pip install nombreLibrería
#Para este ejemplo, utilizaremos la librería pandas, la cual instalaremos


In [ ]:
#Para instalar una versión en especifico, se realiza con el comando
#!pip install nombreLibreria==0.9.0


## Verificar versiones del stack de librerías en el entorno de trabajo

In [ ]:
#Podremos consultar la lista del stack de pibrerias de nuestro entorno de ejecusión en google colab


##Saber sobre una librería en específico

In [ ]:
#Podremos consultar sobre una librería en especifico con el comando help!!!
#Para este caso, consultaremos información de la librería tensorflow
